backend:
  name: github
  repo: nicholasjackson827/ngjackson

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Content, widget: markdown }